# Copyright 2025 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import logging
import os
import shutil
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

import torch
from PIL import Image

from verl.experimental.agent_loop.agent_loop import (
    AgentLoopBase,
    AgentLoopOutput,
    register,
)
from verl.experimental.agent_loop.tool_parser import FunctionCall, ToolParser
from verl.experimental.agent_loop.utils import build_gpt_oss_tool_response_text
from verl.interactions.base import BaseInteraction
from verl.interactions.utils.interaction_registry import initialize_interactions_from_config
from verl.tools.schemas import ToolResponse
from verl.tools.utils.tool_registry import initialize_tools_from_config
from verl.utils.profiler import simple_timer
from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class AgentState(Enum):
    PENDING = "pending"
    GENERATING = "generating"
    PROCESSING_TOOLS = "processing_tools"
    TERMINATED = "terminated"
    INTERACTING = "interacting"


class AgentData:
    """Encapsulates all state variables for the agent loop. AgentData is passed to tool calling in case that
    tool may need to access full history state. User can store any tool session data in `extra_fields`."""

    def __init__(
        self,
        messages: list[dict[str, Any]],
        image_data: list[Image.Image],
        video_data: list[tuple[torch.Tensor, dict[str, Any]]],
        metrics: dict[str, Any],
        request_id: str,
        tools_kwargs: dict[str, Any],
        interaction: Optional[BaseInteraction] = None,
        interaction_kwargs: Optional[dict[str, Any]] = None,
    ):
        self.messages = messages
        self.image_data = image_data
        self.video_data = video_data
        self.metrics = metrics
        self.request_id = request_id
        self.tools_kwargs = tools_kwargs
        self.interaction = interaction
        self.interaction_kwargs = interaction_kwargs or {}

        # State variables
        self.prompt_ids: list[int] = []
        self.response_ids: list[int] = []
        self.response_mask: list[int] = []
        self.response_logprobs: list[float] = []
        self.turn_scores: list[float] = []
        self.tool_rewards: list[float] = []
        self.user_turns = 0
        self.assistant_turns = 0

        # Temporary state for tool calls
        self.tool_calls: list[FunctionCall] = []

        self.routed_experts = None

        # Store last tool execution results for Interaction
        self.last_tool_action: Optional[str] = None
        self.last_processed_image: Optional[str] = None
        self.last_tool_output_path: Optional[str] = None

        # Extra fields for dynamic addition, e.g., tool session data
        self.extra_fields: dict[str, Any] = {}
        # Track temporary directories generated by tools for end-of-trajectory cleanup.
        self.extra_fields["temp_output_dirs"] = set()


@register("tool_agent")
class ToolAgentLoop(AgentLoopBase):
    def __init__(self, *args, cached_tools=None, cached_interactions=None, **kwargs):
        super().__init__(*args, **kwargs)

        # Initialize tools from config file OR use pre-cached tools
        self.max_user_turns = self.rollout_config.multi_turn.max_user_turns
        self.max_assistant_turns = self.rollout_config.multi_turn.max_assistant_turns
        self.max_parallel_calls = self.rollout_config.multi_turn.max_parallel_calls
        self.max_tool_response_length = self.rollout_config.multi_turn.max_tool_response_length
        self.tool_response_truncate_side = self.rollout_config.multi_turn.tool_response_truncate_side
        
        # Use cached tools if provided, otherwise load from config
        if cached_tools is not None:
            logger.info("Using pre-cached tools from worker")
            self.tools = cached_tools
        else:
            tool_config_path = self.rollout_config.multi_turn.tool_config_path
            tool_list = initialize_tools_from_config(tool_config_path) if tool_config_path else []
            self.tools = {tool.name: tool for tool in tool_list}
        
        self.tool_schemas = [tool.tool_schema.model_dump(exclude_unset=True, exclude_none=True) for tool in self.tools.values()]
        self.tool_parser = ToolParser.get_tool_parser(self.rollout_config.multi_turn.format, self.tokenizer)
        self.tool_parser_name = self.rollout_config.multi_turn.format

        self.prompt_length = self.rollout_config.prompt_length
        self.response_length = self.rollout_config.response_length

        # Use cached interactions if provided, otherwise load from config
        self.interaction_config_file = self.rollout_config.multi_turn.interaction_config_path
        if cached_interactions is not None:
            logger.info("Using pre-cached interactions from worker")
            self.interaction_map: dict[str, BaseInteraction] = cached_interactions
        elif self.interaction_config_file:
            self.interaction_map: dict[str, BaseInteraction] = self._initialize_interactions(
                self.interaction_config_file
            )
        else:
            self.interaction_map = {}

    @rollout_trace_op
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        messages = list(kwargs["raw_prompt"])

        # extract images and videos from messages
        multi_modal_data = await self.process_vision_info(messages)
        images = multi_modal_data.get("images")
        videos = multi_modal_data.get("videos")

        metrics = {}
        request_id = uuid4().hex
        
        # Get tools_kwargs from extra_info (where dataset stores it)
        extra_info = kwargs.get("extra_info", {})
        tools_kwargs = extra_info.get("tools_kwargs", kwargs.get("tools_kwargs", {}))

        # Initialize interaction if needed
        interaction = None
        interaction_kwargs = {}
        if self.interaction_config_file:
            interaction_kwargs = kwargs["extra_info"]["interaction_kwargs"]
            if "name" not in interaction_kwargs:
                raise ValueError("'name' key is required in interaction_kwargs")
            interaction_name = interaction_kwargs["name"]
            if interaction_name not in self.interaction_map:
                raise ValueError(
                    f"Interaction '{interaction_name}' not found in interaction_map. Available interactions: "
                    f"{list(self.interaction_map.keys())}"
                )
            interaction = self.interaction_map[interaction_name]
            await interaction.start_interaction(request_id, **interaction_kwargs)
        # Create AgentData instance to encapsulate all state
        agent_data = AgentData(
            messages=messages,
            image_data=images,
            video_data=videos,
            metrics=metrics,
            request_id=request_id,
            tools_kwargs=tools_kwargs,
            interaction=interaction,
            interaction_kwargs=interaction_kwargs,
        )

        try:
            # State machine loop
            state = AgentState.PENDING
            while state != AgentState.TERMINATED:
                if state == AgentState.PENDING:
                    state = await self._handle_pending_state(agent_data, sampling_params)
                elif state == AgentState.GENERATING:
                    state = await self._handle_generating_state(agent_data, sampling_params)
                elif state == AgentState.PROCESSING_TOOLS:
                    state = await self._handle_processing_tools_state(agent_data)
                elif state == AgentState.INTERACTING:
                    state = await self._handle_interacting_state(agent_data)
                else:
                    logger.error(f"Invalid state: {state}")
                    state = AgentState.TERMINATED

            # Finalize output
            response_ids = agent_data.prompt_ids[-len(agent_data.response_mask) :]
            prompt_ids = agent_data.prompt_ids[: len(agent_data.prompt_ids) - len(agent_data.response_mask)]
            multi_modal_data = {}
            if agent_data.image_data is not None:
                multi_modal_data["images"] = agent_data.image_data
            if agent_data.video_data is not None:
                multi_modal_data["videos"] = agent_data.video_data
            
            # Aggregate turn_scores from Interaction as final reward_score
            # This allows Interaction-based reward to skip separate RewardManager computation
            # IMPORTANT: Always set a default reward to avoid triggering NaiveRewardManager
            final_reward_score = 0.0  # Default to 0.0 instead of None
            if agent_data.turn_scores:
                # Sum all turn scores as the final reward
                final_reward_score = sum(agent_data.turn_scores)
            
            output = AgentLoopOutput(
                prompt_ids=prompt_ids,
                response_ids=response_ids[: self.response_length],
                response_mask=agent_data.response_mask[: self.response_length],
                multi_modal_data=multi_modal_data,
                response_logprobs=agent_data.response_logprobs[: self.response_length]
                if agent_data.response_logprobs
                else None,
                num_turns=agent_data.user_turns + agent_data.assistant_turns + 1,
                metrics=agent_data.metrics,
                routed_experts=agent_data.routed_experts,
                extra_fields={},
                reward_score=final_reward_score,  # Use aggregated turn_scores as reward
            )
            output.extra_fields.update({"turn_scores": agent_data.turn_scores, "tool_rewards": agent_data.tool_rewards})
            return output
        finally:
            await self._finalize_interaction_and_cleanup(agent_data)

    async def _handle_pending_state(self, agent_data: AgentData, sampling_params: dict[str, Any]) -> AgentState:
        """Handle the pending state: prepare the prompt and start generation."""
        # For 'answer' format parser, don't inject OpenAI tool schemas into prompt
        # The model is expected to output <answer>tool_name</answer> directly
        # based on instructions in the system prompt, not OpenAI function calling format
        tools_to_inject = None if self.tool_parser_name == "answer" else self.tool_schemas
        
        prompt_ids = await self.apply_chat_template(
            agent_data.messages,
            tools=tools_to_inject,
            images=agent_data.image_data,
            videos=agent_data.video_data,
        )
        agent_data.prompt_ids = prompt_ids
        return AgentState.GENERATING

    async def _handle_generating_state(
        self, agent_data: AgentData, sampling_params: dict[str, Any], ignore_termination: bool = False
    ) -> AgentState:
        """Handle the generating state: generate model response and check for tool calls."""
        add_messages: list[dict[str, Any]] = []

        with simple_timer("generate_sequences", agent_data.metrics):
            output = await self.server_manager.generate(
                request_id=agent_data.request_id,
                prompt_ids=agent_data.prompt_ids,
                sampling_params=sampling_params,
                image_data=agent_data.image_data,
                video_data=agent_data.video_data,
            )
        # first time to set num_preempted
        if agent_data.metrics.get("num_preempted") is None:
            agent_data.metrics["num_preempted"] = output.num_preempted if output.num_preempted is not None else -1
        # then add num_preempted to the metrics
        else:
            agent_data.metrics["num_preempted"] += output.num_preempted if output.num_preempted is not None else 0

        agent_data.assistant_turns += 1
        agent_data.response_ids = output.token_ids
        agent_data.prompt_ids += agent_data.response_ids
        agent_data.response_mask += [1] * len(agent_data.response_ids)
        if output.log_probs:
            agent_data.response_logprobs += output.log_probs

        if output.routed_experts is not None:
            agent_data.routed_experts = output.routed_experts

        # Check termination conditions
        if not ignore_termination and len(agent_data.response_mask) >= self.response_length:
            return AgentState.TERMINATED
        if self.max_assistant_turns and agent_data.assistant_turns >= self.max_assistant_turns:
            return AgentState.TERMINATED
        if self.max_user_turns and agent_data.user_turns >= self.max_user_turns:
            return AgentState.TERMINATED

        # Extract tool calls
        _, agent_data.tool_calls = await self.tool_parser.extract_tool_calls(agent_data.response_ids)

        # Handle interaction if needed
        if self.interaction_config_file:
            assistant_message = await self.loop.run_in_executor(
                None, lambda: self.tokenizer.decode(agent_data.response_ids, skip_special_tokens=True)
            )
            add_messages.append({"role": "assistant", "content": assistant_message})
            agent_data.messages.extend(add_messages)

        # Determine next state
        if agent_data.tool_calls:
            return AgentState.PROCESSING_TOOLS
        elif self.interaction_config_file:
            return AgentState.INTERACTING
        else:
            return AgentState.TERMINATED

    async def _handle_processing_tools_state(self, agent_data: AgentData) -> AgentState:
        """Handle the processing tools state: execute tool calls and prepare tool responses.
        
        If Interaction is configured, the Interaction feedback is appended to the last
        tool response message to maintain the standard assistant → tool → assistant alternation.
        """
        add_messages: list[dict[str, Any]] = []
        new_images_this_turn: list[Any] = []  # Local variable instead of agent_data attribute

        tasks = []
        tool_call_infos = []  # Store both tool name and actual action
        for tool_call in agent_data.tool_calls[: self.max_parallel_calls]:
            tasks.append(self._call_tool(tool_call, agent_data.tools_kwargs, agent_data))
            # Extract actual action from arguments for Interaction
            # For AnswerToolParser: FunctionCall(name="restore_image", arguments='{"action": "ridcp"}')
            actual_action = tool_call.name  # Default to tool name
            try:
                if tool_call.arguments:
                    args = json.loads(tool_call.arguments)
                    actual_action = args.get("action", tool_call.name)
            except (json.JSONDecodeError, TypeError):
                pass
            tool_call_infos.append({"name": tool_call.name, "action": actual_action})

        with simple_timer("tool_calls", agent_data.metrics):
            responses = await asyncio.gather(*tasks)

        # Store the last tool execution info for Interaction
        # Use the ACTUAL action (e.g., "stop", "ridcp") not the tool name ("restore_image")
        if tool_call_infos:
            agent_data.last_tool_action = tool_call_infos[0]["action"]
            logger.info(f"Tool action extracted: {agent_data.last_tool_action} (tool: {tool_call_infos[0]['name']})")
        
        # Process tool responses and update multi_modal_data
        for idx, (tool_response, tool_reward, res) in enumerate(responses):
            # Extract output_path from tool execution result for Interaction
            if idx == 0 and isinstance(res, dict):
                agent_data.last_tool_output_path = res.get("output_path")
                agent_data.last_processed_image = res.get("output_path")
            if isinstance(res, dict):
                output_path = res.get("output_path")
                if output_path:
                    parent_dir = os.path.dirname(str(output_path))
                    if parent_dir:
                        agent_data.extra_fields["temp_output_dirs"].add(parent_dir)
            
            # Create message from tool response
            if tool_response.image or tool_response.video:
                # Multi-modal content with structured format
                # Qwen-VL chat template natively supports images in "tool" role with
                # <|vision_start|><|image_pad|><|vision_end|> format
                if not getattr(self.processor, "image_processor", None):
                    raise ValueError(
                        "Multimedia data can only be processed by `processor`, but the processor is None. "
                        "This error is often caused if you are using a LLM model but your tool returns multimodal "
                        "data. Plase use a vlm as the base model."
                    )
                content = []
                if tool_response.image:
                    content.append({"type": "image"})
                if tool_response.video:
                    content.append({"type": "video"})
                if tool_response.text:
                    content.append({"type": "text", "text": tool_response.text})
                # Use standard "tool" role - Qwen chat template handles images correctly
                message = {"role": "tool", "content": content}
            else:
                # Text-only tool response
                message = {"role": "tool", "content": tool_response.text or ""}

            add_messages.append(message)

            # Handle image data
            if tool_response.image:
                # Add new image data
                if isinstance(tool_response.image, list):
                    for img in tool_response.image:
                        if img is not None:
                            new_images_this_turn.append(img)
                else:
                    if tool_response.image is not None:
                        new_images_this_turn.append(tool_response.image)

            # Handle video data
            if tool_response.video:
                logger.warning("Multimedia type 'video' is not currently supported. Only 'image' is supported.")
                raise NotImplementedError(
                    "Multimedia type 'video' is not currently supported. Only 'image' is supported."
                )

            if tool_reward is not None:
                agent_data.tool_rewards.append(tool_reward)

        # === INTERACTION: Calculate reward and append feedback to tool response ===
        # This maintains the standard assistant → tool → assistant alternation
        should_terminate_from_interaction = False
        if self.interaction_config_file and agent_data.interaction:
            interaction_extra_kwargs = {
                "action": agent_data.last_tool_action or "unknown",
                "processed_image": agent_data.last_processed_image,
                "output_path": agent_data.last_tool_output_path,
            }
            
            (
                should_terminate_from_interaction,
                interaction_response,
                reward,
                metrics,
            ) = await agent_data.interaction.generate_response(
                agent_data.request_id, agent_data.messages + add_messages,
                **agent_data.interaction_kwargs,
                **interaction_extra_kwargs
            )
            
            if reward is not None:
                agent_data.turn_scores.append(reward)
            
            # Append interaction feedback to the last tool message
            if interaction_response and add_messages:
                last_msg = add_messages[-1]
                if isinstance(last_msg.get("content"), list):
                    # Multi-modal content: append text block
                    last_msg["content"].append({"type": "text", "text": f"\n\n{interaction_response}"})
                elif isinstance(last_msg.get("content"), str):
                    # Text content: append directly
                    last_msg["content"] = f"{last_msg['content']}\n\n{interaction_response}"
            
            # Clear tool execution state (for Interaction tracking)
            # NOTE: Keep last_tool_output_path for multi-turn chained image processing!
            # This allows subsequent tool calls to use the previous output as input.
            agent_data.last_tool_action = None
            agent_data.last_processed_image = None
            # agent_data.last_tool_output_path is intentionally NOT cleared
            # to support chained image restoration across turns
            
            logger.info(f"Interaction feedback appended, reward={reward}, terminate={should_terminate_from_interaction}")

        agent_data.messages.extend(add_messages)

        if self.tool_parser_name == "gpt-oss":
            logger.info("manually format tool responses for gpt-oss")
            tool_names = [info["name"] for info in tool_call_infos]
            tool_response_text = build_gpt_oss_tool_response_text(add_messages, tool_names)
            response_ids = await self.loop.run_in_executor(
                None, lambda: self.tokenizer.encode(tool_response_text, add_special_tokens=False)
            )
        else:
            images = new_images_this_turn if new_images_this_turn else None
            videos = None
            # Always add_generation_prompt=True because next is model generation
            # (tool → assistant alternation)
            response_ids = await self.apply_chat_template(
                add_messages,
                images=images,
                videos=videos,
                remove_system_prompt=True,
                add_generation_prompt=True,
            )

        if len(agent_data.response_mask) + len(response_ids) >= self.response_length:
            return AgentState.TERMINATED
        # Update prompt_ids and response_mask

        if new_images_this_turn:
            if agent_data.image_data is None:
                agent_data.image_data = []
            elif not isinstance(agent_data.image_data, list):
                agent_data.image_data = [agent_data.image_data]
            for img in new_images_this_turn:
                agent_data.image_data.append(img)

        agent_data.prompt_ids += response_ids
        agent_data.response_mask += [0] * len(response_ids)
        if agent_data.response_logprobs:
            agent_data.response_logprobs += [0.0] * len(response_ids)
        agent_data.user_turns += 1
        
        # Check if Interaction requested termination (e.g., "stop" action or max iterations)
        if should_terminate_from_interaction:
            return AgentState.TERMINATED
        else:
            return AgentState.GENERATING

    async def _handle_interacting_state(self, agent_data: AgentData) -> AgentState:
        """Handle the interacting state: standalone interaction without tool calls.
        
        NOTE: This method is now mainly for cases where Interaction is triggered
        without tool calls (e.g., model generates a response without calling tools).
        For tool-based interactions, the feedback is now merged into _handle_processing_tools_state.
        
        This state calculates rewards and generates feedback for the model.
        It passes the last tool execution results (action, processed_image) to the Interaction.
        """
        # Pass tool execution results to Interaction for reward calculation
        interaction_extra_kwargs = {
            "action": agent_data.last_tool_action or "unknown",
            "processed_image": agent_data.last_processed_image,
            "output_path": agent_data.last_tool_output_path,
        }
        
        (
            should_terminate_sequence,
            interaction_responses,
            reward,
            metrics,
        ) = await agent_data.interaction.generate_response(
            agent_data.request_id, agent_data.messages, 
            **agent_data.interaction_kwargs,
            **interaction_extra_kwargs  # Pass tool results
        )
        agent_data.user_turns += 1
        
        # Clear the tool execution state after processing
        # NOTE: Keep last_tool_output_path for multi-turn chained image processing!
        agent_data.last_tool_action = None
        agent_data.last_processed_image = None
        # agent_data.last_tool_output_path is intentionally NOT cleared

        add_messages: list[dict[str, Any]] = [{"role": "user", "content": interaction_responses}]
        agent_data.messages.extend(add_messages)

        if reward is not None:
            agent_data.turn_scores.append(reward)

        # Update prompt with user responses (similar to _handle_processing_tools_state)
        response_ids = await self.apply_chat_template(
            add_messages,
            remove_system_prompt=True,
        )

        # Update prompt_ids and response_mask
        agent_data.prompt_ids += response_ids
        agent_data.response_mask += [0] * len(response_ids)
        if agent_data.response_logprobs:
            agent_data.response_logprobs += [0.0] * len(response_ids)

        # double check prompt
        # Check termination condition
        if should_terminate_sequence:
            return AgentState.TERMINATED
        else:
            return AgentState.GENERATING

    async def _call_tool(
        self, tool_call: FunctionCall, tools_kwargs: dict[str, Any], agent_data: AgentData
    ) -> tuple[ToolResponse, float, dict]:
        """Call tool and return tool response."""
        tool, instance_id = None, None
        try:
            # TODO: append malformed tool_call to the prompt: invalid function name or arguments
            tool_name = tool_call.name
            tool_args = json.loads(tool_call.arguments)
            tool = self.tools[tool_name]
            kwargs = tools_kwargs.get(tool_name, {})
            create_kwargs = dict(kwargs.get("create_kwargs", {}))  # Make a copy to avoid mutating original
            
            # CRITICAL FIX: For multi-turn image restoration, use the previous turn's output
            # as the current turn's input image. Without this, each turn would process
            # the original image instead of the chain of processed images.
            if agent_data.last_tool_output_path:
                # Override original_image with previous turn's output for chained processing
                create_kwargs["original_image"] = agent_data.last_tool_output_path
                logger.info(f"Using previous turn's output as input: {agent_data.last_tool_output_path}")
            
            instance_id, _ = await tool.create(**create_kwargs)
            tool_execution_response, tool_reward, res = await tool.execute(
                instance_id, tool_args, agent_data=agent_data
            )
        except Exception as e:
            logger.warning(f"Error when executing tool: {e}")
            return (
                ToolResponse(
                    text=f"Error when executing tool: {e}",
                ),
                0.0,
                {},
            )
        finally:
            if tool and instance_id:
                await tool.release(instance_id)

        tool_response_text = tool_execution_response.text
        if tool_response_text and len(tool_response_text) > self.max_tool_response_length:
            if self.tool_response_truncate_side == "left":
                tool_response_text = tool_response_text[: self.max_tool_response_length] + "...(truncated)"
            elif self.tool_response_truncate_side == "right":
                tool_response_text = "(truncated)..." + tool_response_text[-self.max_tool_response_length :]
            else:
                length = self.max_tool_response_length // 2
                tool_response_text = tool_response_text[:length] + "...(truncated)..." + tool_response_text[-length:]

        # Create ToolResponse from tool execution result
        tool_response_kwargs = {"text": tool_response_text}

        # Add multimedia data if present
        for attr_name in ["image", "video"]:
            if hasattr(tool_execution_response, attr_name):
                attr_value = getattr(tool_execution_response, attr_name)
                if attr_value is not None:
                    tool_response_kwargs[attr_name] = attr_value

        return ToolResponse(**tool_response_kwargs), tool_reward, res

    def _initialize_interactions(self, interaction_config_file):
        """Initialize interactions from configuration.
        Returns:
            dict[str, BaseInteraction]: A dictionary mapping interaction names to interaction instances.
        """
        if interaction_config_file is None:
            return {}

        interaction_map = initialize_interactions_from_config(interaction_config_file)
        return interaction_map

    async def _finalize_interaction_and_cleanup(self, agent_data: AgentData) -> None:
        """Finalize interaction and clean temporary tool outputs generated in this trajectory."""
        if agent_data.interaction:
            try:
                await agent_data.interaction.finalize_interaction(agent_data.request_id)
            except Exception as e:
                logger.warning(f"Failed to finalize interaction {agent_data.request_id}: {e}")

        cleanup_enabled = getattr(self.rollout_config.multi_turn, "cleanup_temporary_outputs", True)
        if not cleanup_enabled:
            return

        temp_dirs = agent_data.extra_fields.get("temp_output_dirs", set())
        if not temp_dirs:
            return

        for temp_dir in sorted(temp_dirs):
            if not temp_dir:
                continue
            try:
                if os.path.isdir(temp_dir):
                    shutil.rmtree(temp_dir, ignore_errors=True)
            except Exception as e:
                logger.warning(f"Failed to cleanup temp dir {temp_dir}: {e}")
